// Don't currently have the repo with all of my other notes. Continuing where I
//   left
//  off(Ch4 system faults)

//  Oops Messages
//  =============
//  generated by printk statements in fault handler
//  (arch/*/kernel/traps.c)
//
//  TODO: come back here to learn how to deal with oops messages
//      when/if i start getting them

//  System Hangs
//  ============
//  Prevent infinite loop by inserting `schedule` invocations
//  at strategic points. This call invokes scheduler and allows
//  you to schedule other processes.
//
//  Do not use `schedule` if holding a spinlock or other lock.
//
//  Magic SysRq key: see Documentation/sysrq.txt
