// Don't currently have the repo with all of my other notes. Continuing where I
//   left
//  off(Ch4 system faults)

//  Oops Messages
//  =============
//  generated by printk statements in fault handler
//  (arch/*/kernel/traps.c)
//
//  TODO: come back here to learn how to deal with oops messages
//      when/if i start getting them

//  System Hangs
//  ============
//  Prevent infinite loop by inserting `schedule` invocations
//  at strategic points. This call invokes scheduler and allows
//  you to schedule other processes.
//
//  Do not use `schedule` if holding a spinlock or other lock.
//
//  Node the above may be irrelevant in multiprocessing systems
//
//  Magic SysRq key: see Documentation/sysrq.txt
//
//
//  GDB for debugging
//  =================
//  specify name for elf kernel image and name of core file
//  for a running kernel, core file is kernel core image
//  gdb /usr/src/linux/vmlinux /proc/kcore
//
//  kcore represents whole kernel addr space, corresponding to all physmem
//  can look at kernel variables by using gdb commands.
//  e.g. `p jiffies` to print num clock ticks from sysboot to curtime
//
//  gdb caches values, so have to command `core-file /proc/kcore`
//  when want to flush gdb cache
//
//  must compile kernel with CONFIG_DEBUG_INFO for symbol info in gdb
//
//  Debugging modules:
//  3 main important sections .text, .bss (uninit) , .data (init'd)
//  must inform gdb where each section has been loaded.
//  base addr for each section is in /sys/module/<modname>/sections
//
//  gdb command `add-symbol-file`
//  e.g. `add-symbol-file scull.ko 0x<textbaseaddr> \
//          -s .bss <addr> -s .data <addr>`
//
//  `print *(address)`
//  output is file and line number for code corresponding to addr
//  e.g. find where a function pointer really points
//
//  kernel debugger
//  ===============
//  nonofficial patch from oss.sgi.com
//
//  press Pause or Break key on a console to start debugger.
//  also starts when oops happens or breakpooiint hit.
//
//  good idea disable networking, etc. (e.g. SingUserMode) when kdb
//
//
//  kgdb
//  ====
//  more patches called kgdb allow for kern debug w/ more capabilities
//
//
//
//  User Mode Linux
//  ===============
